### PR TITLE
[FIX] #134 addVolumeListener is not triggered on iOS 15

### PR DESCRIPTION
**Pull request by Igor-Tiukavkin**
### Issue 
**Number #134: iOS 15 addVolumeListener fix**

The system volume observer is no longer working on iOS 15.

**Steps for reproduce:**
1. Add system volume did change observer
2. Play any media
2. Change volume with hardware buttons at the device
3. Change volume with volume control in the app

**Expected behaviour:**
Change of volume setting value is processed correctly 

**Current Result:**
Hardware buttons volume change has no response. 
**NotificationCenter** produces no notifications for key **AVSystemController_SystemVolumeDidChangeNotification**.

### Problem:

There is an information on [stackoverflow](https://stackoverflow.com/questions/68249775/system-volume-change-observer-not-working-on-ios-15) that observing of **AVSystemController_SystemVolumeDidChangeNotification** is no longer supported because it's a private API.

### Solution

The solution is based on the answer: _**EWTDTHK2** [commented on 3 Oct](https://github.com/c19354837/react-native-system-setting/issues/134#issuecomment-932981104)_.
The correct approach is to add KVO observer for **AVAudioSession** instance for **outputVolume** keyPath.

### CODE REVIEW

**Review by CHaNGeTe — APPROVED** [review]

**Comment by MrHjalmarsson** [comment]
Thanks for a very useful package!
Does anyone have an idea about when this PR will be merged?
Would be greatly appreciated if it could happen rather sooner than later. :)

**Comment by Shummy1991** [comment]
You can use patch-package until it is merged.

**Comment by MrHjalmarsson** [comment]
Thanks, @Shummy1991! Will try that!

**Review by kot331107 — APPROVED** [review]
lgtm

**Comment by kolking** [comment]
@c19354837 please publish a new release with this fix included.

**Comment by buildgreatthings** [comment]
@c19354837 please publish a new release with this fix included.

**Comment by kot331107** [comment]
@awcchungster would `patch-package` work with you till guys won't publish it?

**Comment by arjun-zosma** [comment]
This doesn't work if the app goes into background and then into foreground.

**Pull request merged**
