### PR TITLE
Opt in Android permissions

### PR DESCRIPTION
**Pull request by Gregoirevda**
Current:
- delete the permission in the AndroidManifest in the node_modules

If you clone the repo again and yarn permissions will be reset.

PR
No default permissions, add in README to add permissions in app AndroidManifest.xml

### CODE REVIEW

**Comment by c19354837** [comment]
Thanks for your PR.

This would cause a breaking change. 

I consider to merge it in V 1.5.0.

**Comment by Gregoirevda** [comment]
Thanks, would be great for us!

**Comment by c19354837** [comment]
V1.5.0 is available!

I've updated the README on your basis.

**Comment by Gregoirevda** [comment]
Thanks!!

**Pull request merged**
