### PR TITLE
Makes sure setVolume(val, config) sets default for all options

### PR DESCRIPTION
**Pull request by alexanderwallin**
This addresses #22. Currently, you have to specify all configs.

I have not properly tested this, but thought maybe it would save you some time. Do what you wish with it!

### CODE REVIEW

**Comment by c19354837** [comment]
Thank you.

**Comment by c19354837** [comment]
`Object.extend()` should be `Object.assign()` -_-!

I have fixed it.

**Comment by c19354837** [comment]
`Object.extend()` should be `Object.assign()`  -_-!  

I have fixed it.

I have no device to test it now, so new version will be published this weekend.

**Comment by alexanderwallin** [comment]
> Object.extend() should be Object.assign() -_-!

Ah, yes of course! Thanks for tending to this so quickly.

**Pull request merged**
